#!/usr/bin/env python3
"""ChatGPT Ada/Code Interpreter helper: upscale x8 and create an A4 PDF.

Usage inside Code Interpreter:
    from ada_upscale_a4_pdf import build_a4_pdf
    build_a4_pdf('/mnt/data/generated_mini_cad.png')

The script is deterministic and uses Pillow only. It preserves aspect ratio,
places the upscaled drawing on an A4 white page, and avoids adding new content.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict

from PIL import Image, ImageOps

A4_PORTRAIT_MM = (210, 297)
A4_LANDSCAPE_MM = (297, 210)
DEFAULT_DPI = 300
DEFAULT_MARGIN_MM = 8


def _mm_to_px(mm: float, dpi: int) -> int:
    return round(mm / 25.4 * dpi)


def _a4_size_px(landscape: bool, dpi: int) -> tuple[int, int]:
    width_mm, height_mm = A4_LANDSCAPE_MM if landscape else A4_PORTRAIT_MM
    return _mm_to_px(width_mm, dpi), _mm_to_px(height_mm, dpi)


def upscale_x8(input_path: str | Path, output_path: str | Path | None = None) -> Path:
    """Create an 8x raster upscale with high-quality Lanczos resampling."""
    source = Path(input_path)
    if output_path is None:
        output_path = source.with_name(f"{source.stem}_x8.png")
    target = Path(output_path)
    image = Image.open(source).convert("RGB")
    upscaled = image.resize((image.width * 8, image.height * 8), Image.Resampling.LANCZOS)
    upscaled.save(target, optimize=True)
    return target


def make_a4_pdf(
    image_path: str | Path,
    output_pdf: str | Path | None = None,
    dpi: int = DEFAULT_DPI,
    margin_mm: int = DEFAULT_MARGIN_MM,
) -> Path:
    """Place an image on a white A4 page and export a print-ready PDF."""
    source = Path(image_path)
    if output_pdf is None:
        output_pdf = source.with_name(f"{source.stem}_A4.pdf")
    target = Path(output_pdf)

    image = Image.open(source).convert("RGB")
    landscape = image.width >= image.height
    page_w, page_h = _a4_size_px(landscape=landscape, dpi=dpi)
    margin = _mm_to_px(margin_mm, dpi)
    box_w, box_h = page_w - 2 * margin, page_h - 2 * margin

    fitted = ImageOps.contain(image, (box_w, box_h), method=Image.Resampling.LANCZOS)
    page = Image.new("RGB", (page_w, page_h), "white")
    x = (page_w - fitted.width) // 2
    y = (page_h - fitted.height) // 2
    page.paste(fitted, (x, y))
    page.save(target, "PDF", resolution=float(dpi))
    return target


def build_a4_pdf(input_path: str | Path, dpi: int = DEFAULT_DPI, margin_mm: int = DEFAULT_MARGIN_MM) -> Dict[str, str]:
    """Production one-call flow: PNG x8 plus final A4 PDF."""
    x8_png = upscale_x8(input_path)
    pdf = make_a4_pdf(x8_png, dpi=dpi, margin_mm=margin_mm)
    return {"png_x8": str(x8_png), "pdf_a4": str(pdf)}


if __name__ == "__main__":
    import argparse
    import json

    parser = argparse.ArgumentParser(description="Upscale a mini-CAD image x8 and create an A4 PDF.")
    parser.add_argument("image", help="Input PNG/JPG generated by @Stwórz Obraz or SelfEngine")
    parser.add_argument("--dpi", type=int, default=DEFAULT_DPI)
    parser.add_argument("--margin-mm", type=int, default=DEFAULT_MARGIN_MM)
    args = parser.parse_args()
    print(json.dumps(build_a4_pdf(args.image, dpi=args.dpi, margin_mm=args.margin_mm), indent=2, ensure_ascii=False))
